def initialize() {
  try {
    stage('build app-store-service') {
      sh '''cd app-store-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return currentBuild.result ?: 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'app-store-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'app-store-service-detekt-Report', reportTitles: ''])
  }
  try {
    stage('test app-store-service') {
      sh '''cd app-store-service
      ./gradlew test'''
    }
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}

return this
