#
# Production container copying from locally build artifact
#

FROM alpine:3.8 as production-cached

ENV JAVA_HOME=/usr/lib/jvm/default-jvm \
    PATH=$PATH:$JAVA_HOME/jre/bin:$JAVA_HOME/bin

RUN apk add --no-cache openjdk8-jre
RUN apk add --no-cache nss

COPY build/service /opt/service/

CMD ["/opt/service/bin/service"]
