#!/bin/bash

OUTPUT_FILE="../mail_templates.go"

cat <<EOF > "$OUTPUT_FILE"
package foundation

import _ "embed"

// Generated by mailtpl/generate.sh. Please run the script from the mailtpl folder.

EOF

find . -type f -name '*.j2' | while read -r file; do
  embedded_path="mailtpl/${file#./}"

  file_no_ext="${file%.j2}"
  var_name=$(echo "$file_no_ext" | sed -E 's|[^a-zA-Z0-9]| |g' | awk '{for (i=1;i<=NF;i++) printf toupper(substr($i,1,1)) tolower(substr($i,2))} END {print ""}')
  var_name="tpl$var_name"

  echo "//go:embed $embedded_path" >> "$OUTPUT_FILE"
  echo "var $var_name []byte" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
done
