// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class AuthenticateRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AuthenticateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAuthenticateRequest(bb:flatbuffers.ByteBuffer, obj?:AuthenticateRequest):AuthenticateRequest {
  return (obj || new AuthenticateRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAuthenticateRequest(bb:flatbuffers.ByteBuffer, obj?:AuthenticateRequest):AuthenticateRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AuthenticateRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bearer():string|null
bearer(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
bearer(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startAuthenticateRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBearer(builder:flatbuffers.Builder, bearerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, bearerOffset, 0);
}

static endAuthenticateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // bearer
  return offset;
}

static createAuthenticateRequest(builder:flatbuffers.Builder, bearerOffset:flatbuffers.Offset):flatbuffers.Offset {
  AuthenticateRequest.startAuthenticateRequest(builder);
  AuthenticateRequest.addBearer(builder, bearerOffset);
  return AuthenticateRequest.endAuthenticateRequest(builder);
}
}
