#!/usr/bin/env bash
# -*- coding: utf-8 -*-
realpath() (
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
)


mkdir -p /tmp/ucloud-launcher
repo_root=$(dirname $(realpath $0))
cd $repo_root/launcher-tool-go
log_file=/tmp/ucloud-launcher/$(uuidgen)

cd $repo_root/launcher-tool-go

post_exec=/tmp/ucloud-launcher/$(uuidgen)
go run cmd/launcher/main.go $post_exec $@
if test -f $post_exec; then
    cat $post_exec
    bash $post_exec
fi
rm -f $post_exec
