#!/usr/bin/env bash
# -*- coding: utf-8 -*-
mkdir -p /tmp/ucloud-launcher
repo_root=$(dirname $(realpath $0))
cd $repo_root/launcher-tool
log_file=/tmp/ucloud-launcher/$(uuidgen)
./gradlew installDist --console=plain &> $log_file
if [ $? != 0 ]; then
    echo "Unable to start launcher tool. Perhaps you are missing a dependency?"
    cat $log_file
    exit 1
fi
cd $repo_root

post_exec=/tmp/ucloud-launcher/$(uuidgen)
$repo_root/launcher-tool/build/install/launcher-tool/bin/launcher-tool $post_exec $@
if test -f $post_exec; then
    bash $post_exec
fi
rm -f $post_exec

