#!/usr/bin/env bash
# -*- coding: utf-8 -*-

cd launcher-tool-go
CGO_ENABLED=0 go build -gcflags "all=-N -l" -o ./.launcher-tool -trimpath cmd/launcher-tui/main.go
cd ..

if [[ "${DEBUG:-0}" == "1" ]]; then
    dlv exec launcher-tool-go/.launcher-tool --headless --listen=0.0.0.0:40381 --api-version=2 -- "$@"
else 
    ./launcher-tool-go/.launcher-tool "$@"
fi

