provider:
  id: foobar

  hosts:
    ucloud:
      address: xxxxxxxx
      port: 443
    self:
      address: xxxxxxxx
      port: 443

  ipc:
    directory: /var/run/ucloud

  logs:
    directory: /var/log/ucloud
    rotation:
      enabled: true
      retentionDays: 180

  envoy:
    directory: /var/run/ucloud/envoy
    excutable: /usr/bin/envoy
    funceWrapper: false

services:
  type: Slurm

  identityManagement:
    type: FreeIPA
    config: /etc/ucloud/ipa.yml

  fileSystems:
    u1-ess:
      management:
        type: ESS
        config: /etc/ucloud/ess.yml

      payment:
        type: Resource
        unit: TB

      driveLocators:
        home:
          entity: User
          pattern: "/home/#{username}"

        projects:
          entity: Project
          pattern: "/work/#{title}"

# NOTE(Dan): Not obvious how to do this yet, so we are postponing its consideration.
#        collections:
#          entity: Collection
#          pattern: "/collections/#{id}"

        memberFiles:
          entity: MemberFiles
          pattern: "/projects/#{project}/#{username}"

    u1-generic-storage:
      management:
        type: Scripted

        walletUpdated: "/opt/ucloud/on-storage-wallet-updated"
        fetchUsage: "/opt/ucloud/fetch-storage-usage"

      payment:
        type: Money
        currency: DKK
        unit: TB
        interval: Monthly
        price: 123.456

      driveLocators:
        projects:
          entity: Project
          script: "/opt/ucloud/drive-locator"

  ssh:
    enabled: true
    installKeys: true
    host:
      address: frontend.example.com
      port: 22

  licenses:
    enabled: false

  slurm:
    accountManagement:
      type: Scripted
      walletUpdated: "/opt/ucloud/on-compute-wallet-updated"
      fetchUsage: "/opt/ucloud/on-compute-wallet-updated"
      accountMapper: "/opt/ucloud/on-compute-wallet-updated"

    machines:
      u1-standard:
        partition: standard
        constraint: standard

        nameSuffix: Cpu

        cpu: [ 1,2,4,8,16,32,64 ]
        memory: [ 1,2,4,8,16,32,64 ]

        cpuModel: Model
        memoryModel: Model

        payment:
          type: Resource
          unit: Cpu
          interval: Hourly

      u1-gpu:
        partition: gpu
        constraint: gpu
        nameSuffix: Gpu

        cpu: [ 1,2,4,8,16,32,64 ]
        memory: [ 1,2,4,8,16,32,64 ]
        gpu: [ 1,2,4,8,16,32,64 ]
        price: [ 10.1, 20.2, 30.3, 40.4, 50.5, 60.6, 70.7 ]

        cpuModel: Model
        gpuModel: Model
        memoryModel: Model

        payment:
          type: Money
          currency: DKK
          interval: Hourly

      hippo-hm:
        payment:
          type: Resource
          unit: Cpu
          interval: Hourly

        groups:
          hippo-hm1:
            partition: standard
            constraint: hm1

            nameSuffix: Cpu

            cpu: [ 1,2,4,8,16,32,64 ]
            memory: [ 1,2,4,8,16,32,64 ]

            cpuModel: Model
            memoryModel: Model

          hippo-hm2:
            partition: standard
            constraint: hm2

            nameSuffix: Cpu

            cpu: [ 1,2,4,8,16,32,64 ]
            memory: [ 1,2,4,8,16,32,64 ]

            cpuModel: Model
            memoryModel: Model

          hippo-hm3:
            partition: standard
            constraint: hm3

            nameSuffix: Cpu

            cpu: [ 1,2,4,8,16,32,64 ]
            memory: [ 1,2,4,8,16,32,64 ]

            cpuModel: Model
            memoryModel: Model

