package dk.sdu.cloud.controller.dao
import org.jetbrains.exposed.dao.EntityID
import org.jetbrains.exposed.dao.IntEntity
import org.jetbrains.exposed.dao.IntEntityClass


class Principal_notification_subscriptiontype_relationEntity(id: EntityID<Int>) : IntEntity(id) {
	companion object: IntEntityClass<Principal_notification_subscriptiontype_relationEntity>(Principal_notification_subscriptiontype_relation)

	var modified_ts by Principal_notification_subscriptiontype_relation.modified_ts
	var principalnotificationsubscriptiontyperefid by Principal_notification_subscriptiontype_relation.principalnotificationsubscriptiontyperefid
	var marked_for_delete by Principal_notification_subscriptiontype_relation.marked_for_delete
	var created_ts by Principal_notification_subscriptiontype_relation.created_ts
	var active by Principal_notification_subscriptiontype_relation.active
	var principalrefid by Principal_notification_subscriptiontype_relation.principalrefid
}