def initialize() {
  try {
    stage('build and backend') {
      sh '''cd backend
      ./gradlew clean
      ./gradlew generateBuildConfig
      ./gradlew build'''
    }
  } catch (e) {
    echo "Build Failed"
    def logArray = currentBuild.rawBuild.getLog(50)
    def log = ""
    for (String s : logArray)
    {
        log += s + " ";
    }
    def startIndex = log.indexOf("FAILURE: Build failed with an exception")
    def endIndex = log.indexOf("* Try:")
    if (startIndex == -1) {
        startIndex = 0
    }
    if (endIndex == -1) {
        endIndex = log.length()-1
    }
    return 'FAILURE\n' + 'BackendFailed: \n' + log.substring(startIndex, endIndex)
  } //finally {
    //publishHTML([
    //    allowmissing: false,
    //    alwaysLinkToLastBuild: false,
    //    keepAll: true,
    //    reportDir: 'backend/build/reports/detekt',
    //    reportFiles: 'detekt.html',
    //    reportName: 'Backend Detekt',
    //    reportTitles: ''
    //])
  //}
  return 'SUCCESS'
}

return this
