def initialize() {

  stage('build') {
    sh '''cd zenodo-service
    ./gradlew clean
    ./gradlew build -x test'''
  }

  try {
    stage('test') {
      sh '''cd zenodo-service
      ./gradlew test'''
    } 
  } catch (e) {
      echo "Test FAILED"
  } finally {
    junit '**/zenodo-service/build/test-results/**/*.xml'      
    def currentResult = currentBuild.result ?: 'SUCCESS'
    if (currentResult == 'UNSTABLE') {
      echo "Build is unstable"
    }
    if (currentResult == 'SUCCESS') {
      jacoco  execPattern: '**/**.exec',
              exclusionPattern: '**/zenodo-service/,**/AuthMockingKt.class,**/DatabaseSetupKt.class', 
              sourcePattern: '**/zenodo-service/src/main/kotlin/**'   
    }
  }
}

return this