import * as React from "react";
import {useSearchParams} from "react-router-dom";
import {Button, Flex, MainContainer} from "@/ui-components";
import * as ApiTokens from "@/Applications/ApiTokens/api";
import {useParams} from "react-router-dom";
import {callAPI} from "@/Authentication/DataHook";
import {ProjectSwitcher} from "@/Project/ProjectSwitcher";
import {useProject} from "@/Project/cache";
import {useProjectId} from "@/Project/Api";
import {Client} from "@/Authentication/HttpClientInstance";

export function CliAuth() {
    const { apiToken } = useParams();

    if (apiToken) {
        window.location.href = `http://localhost:8080/auth?token=${encodeURIComponent(apiToken)}`;
    }

    return null;
}

const CliConnectPage: React.FunctionComponent = () => {
    const [searchParams] = useSearchParams();
    const redirect = searchParams.get("redirect");
    const projectId = useProjectId();
    const project = useProject();
    const fetchedProject = project.fetch();

    const isPersonalWorkspace = projectId === undefined;
    const selectedId = isPersonalWorkspace ? (Client.activeUsername ?? "") : projectId;
    const selectedTitle = projectId ? fetchedProject.specification.title : Client.activeUsername ?? "";
    
    const generateToken = React.useCallback(() => {
            void callAPI<ApiTokens.ApiToken>({...ApiTokens.create({
            title: "UCloud-CLI API Token",
            description: "Generated by ucloud-cli",
            requestedPermissions: [],
            expiresAt: Date.now() + 90 * 24 * 60 * 60 * 1000,
            provider: null,
            product: {
                category: "",
                id: "",
                provider: ""
            },

        }),
        projectOverride: isPersonalWorkspace ? undefined : selectedId

    }).then(resp => {
            if (redirect && resp.status.token) {
                const redirectUrl = new URL(redirect);
                redirectUrl.searchParams.set("token", resp.status.token);
                redirectUrl.searchParams.set("projectId", selectedId);
                redirectUrl.searchParams.set("projectTitle", selectedTitle);
                window.location.href = redirectUrl.toString();
            }
        }).catch(err => {
            console.log("Failed to create token: ", err);
        });
    }, [selectedId, selectedTitle, redirect]);


    return <MainContainer
        main={
            <Flex justifyContent={"center"} alignItems={"center"} height={"100vh"} flexDirection="column">
                <Flex justifyContent={"space-between"} gap="10px">
                    <div style={{gap: 0}}>
                        Select project
                        <ProjectSwitcher />
                    </div>
                    <Button marginTop="20px" color="successMain" onClick={generateToken}>Connect with UCloud CLI</Button>
                </Flex>
            </Flex>
        }
    />;
};

export default CliConnectPage;