#!/usr/bin/env python2

# Depends on python-jose
import sys
import traceback
from jose import jwt

PAM_AUTH_ERR = 9
PAM_SUCCESS = 0

# TODO Hardcoded cert...
cert = """-----BEGIN CERTIFICATE-----
MIIFtTCCA52gAwIBAgIJAPRcqNU07UHLMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTcxMjEzMDkyNjEwWhcNMTgxMjEzMDkyNjEwWjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEAwpkmLDVp/uIHCs1VfM95o38Z+GwmnC//1M1h1jmgyWXL5pgoEnrly4km
olhQjUwm3Ut+vvrJcU9NyIgdU5WT90kuCeh/x76h0R7socQ6hvec9NIXpavE6eAq
uQyGP9mvLBk5UBndA+pdnbk5XMtD+i65geu6JUWjbyMFTahCMvsC48EVUm4F7D2M
XWsJT401CeF4WuVTFPkgnU0vq7emzvMoT+kwoXlwz/t1d/hShiMx5+wLvyEzIwwA
qE3MKKcHOerTuU6ejvQGjnspBQhljr3tFjgiSIeV7hYC15W4xhJjnOjNeLfII0xi
ZRGj+i95rYKnknJGxu9sdudsuf9XRcwImCZLsM9owyvlHJtSSY9kiEp8/uFrlM3z
iwXun4nxO389foSJSC0vBlgyz8GZ9cMcUWzBjf2vD1f8LuyOhzlXHPClaGlL5ohv
0XJxBzBp+IT6M5ouoTq3aw8u84hQCxHp3uhEXU1TL9RLWCyMTh5SBTXPReRc1rJz
ldljQ0J5q77fI6yxuA4k9JCRKZ+zS5KiXaj7zI0AYZW3OJ9g5lhqEETgP2Uqpas7
0SetzhJoQaDXz/KBrke8j/OVfHs6JeXuc+CdMqArlINqCe/p3w1cqy7JCjZRpsRa
Uc5Wbjv/TTnl1LhCsQ3y6pkTr7dkHgEjVRKKmQYisv6+hbtCgzUCAwEAAaOBpzCB
pDAdBgNVHQ4EFgQUu0/Dq1Q+P33/DAWUTuv14MTW/hcwdQYDVR0jBG4wbIAUu0/D
q1Q+P33/DAWUTuv14MTW/hehSaRHMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIEwpT
b21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGSCCQD0
XKjVNO1ByzAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4ICAQBQ+/QiqjEe
IC13wpAAE9l09AZkmoYdyseE1CjoEG4gC/xk9PLM0ZQetgg7jga7/tFYGhu721pX
lyrJXl2vqtfpa6micHYZCHq3TnVCsgp8C8ocVQ8McvJu+DxZFqDd/4RwabHumkSZ
/ZWrItRyGKSAwXUGhH/71t5UphB0f+OnUEPUMM0dVhAudl4wubNv/2M3U0qi2S1h
X+wuGHy/8ENdq9CJmS5iWDfRUj3chec9eDr5gYqxD3FcAgVM6sy04mmV2g+LZYUQ
8BtaB/7sl/LYYUFLi3R5PM3rB9VJ3lmkPCK7HqZ2ebICOPdOxvTM/T8FMMmnS0f6
Vq+IVtqE8Em/uGHWZImtewfS7BEY8GD0CkSnVtS4GcJdsPlKMYX6mPiCT7zyFGzK
QwlJcdnj9V4CrXFyyjHyWlDB7vixyRoVjKTr5zm8MVYXyyk/5eXt67nn1o5+AaDI
ziVGO6a/4Ccx+5ojpFy546vzqtAgRe6A17nUmC62VUBUv+bKkatNMEmVQsdyNgYj
CsWphIJDAfYc8LsEvNOJaiDEqeOEjq8JIfjQCQ9t0eiNM2WLGbO4L5IwMGWLLOcb
cxRkBwgpvpDi5/B9xsYEDHfvgdfEfpbPCuFyBCexwr3RDoawxe+k86tZLEBfRM09
+OSskqwGL9A/e6uYQ1YD3ZlR+BGTTJvm2A==
-----END CERTIFICATE-----"""

try:
    all_lines = sys.stdin.read().splitlines()
    username = all_lines[0]
    token = all_lines[1]

    ret = PAM_SUCCESS

    try:
        validated = jwt.decode(token, cert, audience = "irods", algorithms = 'RS256')
        if username != validated['sub']:
            ret = PAM_AUTH_ERR
    except:
        trace = traceback.format_exc()
        print trace
        ret = PAM_AUTH_ERR
except:
    ret = PAM_AUTH_ERR

sys.exit(ret)
