apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipman-deploy
spec:
  selector:
    matchLabels:
      app: ipman-deploy
  template:
    metadata:
      name: ipman-deploy
      labels:
        app: ipman-deploy
    spec:
      containers:
        - image: dreg.cloud.sdu.dk/ucloud/ipman:0.1.4
          name: ipman-deploy
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: ipman-mount
          command:
            - /opt/ipman/install.sh
      volumes:
        - name: ipman-mount
          hostPath:
            path: /var/lib/kubelet/volumeplugins
