# Example file showing the format of secrets.yml (Please don't put any actual secrets in this file. Thank you.)
freeipa:
  url: https://ipa.ucloud
  username: admin
  password: adminadmin
  verifyTls: true

gpfs:
  storage: # This is the product category name
    username: gpfs
    password: gpfspassword
    verifyTls: false
    host:
      address: localhost
      port: 62394
      scheme: http
    mapping:
      home: # This is a locator name
        fileSystem: "gpfs"
        parentFileSet: "home"
        fileSetPattern: "home-#{localUsername}" # This has the same variables as the drive locator has
      projects:
        fileSystem: "gpfs"
        parentFileSet: "work"
        fileSetPattern: "work-#{localGroupName}-#{gid}"
