# Example file showing the format of secrets.yml (Please don't put any actual secrets in this file. Thank you.)
freeipa:
  url: https://ipa.ucloud
  username: admin
  password: adminadmin
  verifyTls: true