provider:
  id: go-slurm

  hosts:
    ucloud:
      address: backend
      port: 8080
      scheme: http
    self:
      address: go-slurm
      port: 8889
      scheme: http
    selfPublic:
      address: go-slurm.localhost.direct
      port: 443
      scheme: https
    ucloudPublic:
      address: ucloud.localhost.direct
      port: 443
      scheme: https

  ipc:
    directory: /var/run/ucloud

  logs:
    directory: /var/log/ucloud
    rotation:
      enabled: true
      retentionPeriodInDays: 180

  envoy:
    directory: /var/run/ucloud/envoy
    executable: /usr/bin/envoy
    funceWrapper: false

services:
  type: Slurm
  unmanaged: true # default is false. When true, most managed features must be turned off. It is an error to define them.

  fileSystems:
    storage:
      # NOTE: management must be left blank

      payment:
        type: Resource
        unit: GB

      driveLocators:
        home:
          # NOTE: no entity
          pattern: "/gpfs/home"
          title: "Home"

        projects:
          # NOTE: no entity
          pattern: "/gpfs/work"
          title: "Work"

  ssh:
    enabled: true
    installKeys: true
    host:
      address: frontend.localhost.direct
      port: 22

  licenses:
    enabled: false

  slurm:
    fakeResourceAllocation: true
    # NOTE: accountManagement must be left blank, which will make it unmanaged

    web:
      enabled: true
      prefix: "goslurm-"
      suffix: ".localhost.direct"

    machines:
      u1-standard:
        partition: normal
        qos: standard
        # constraint: standard

        nameSuffix: Cpu

        cpu: [ 1, 2, 4 ]
        memory: [ 1, 2, 4 ]

        cpuModel: Model
        memoryModel: Model

        payment:
          type: Resource
          unit: Cpu
          interval: Hourly
