application: v2

name: generic-ubuntu
version: 1

software:
  type: Container
  image: ubuntu:24.04

features:
  multiNode: true

parameters:
  wf:
    type: Workflow
    optional: false
    title: "Workflow"
    description: |
      Change this workflow to customize what the batch script should do.

    init: ""

    job: |
      sleep inf
    readme: This is a minimal example.

invocation: ""
