---

master:
  serviceType: ClusterIP

  resources:
    requests:
      cpu: 2000m
      memory: 2048Mi
    limits:
      cpu: 8000m
      memory: 8192Mi
  scriptApproval:
    - "method hudson.model.Actionable getActions"
    - "method hudson.model.Run getPreviousSuccessfulBuild"
    - "method jenkins.plugins.git.AbstractGitSCMSource$SCMRevisionImpl getHash"
    - "method jenkins.scm.api.SCMRevisionAction getRevision"
    - "method org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper getRawBuild"
    - "method org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper getRawBuild"
  installPlugins:
    - "blueocean-bitbucket-pipeline:1.8.4"
    - "jdk-tool:1.1"
    - "docker-commons:1.13"
    - "jsch:0.1.54.2"
    - "slack:2.3"
    - "blueocean-i18n:1.8.4"
    - "cobertura:1.13"
    - "ace-editor:1.1"
    - "command-launcher:1.2"
    - "mercurial:2.4"
    - "pipeline-stage-tags-metadata:1.3.2"
    - "workflow-job:2.25"
    - "credentials-binding:1.16"
    - "durable-task:1.26"
    - "ssh-credentials:1.14"
    - "mailer:1.21"
    - "workflow-scm-step:2.7"
    - "blueocean-core-js:1.8.4"
    - "apache-httpcomponents-client-4-api:4.5.5-3.0"
    - "workflow-cps-global-lib:2.12"
    - "cloudbees-bitbucket-branch-source:2.2.12"
    - "momentjs:1.1.1"
    - "pipeline-model-definition:1.3.2"
    - "blueocean-autofavorite:1.2.2"
    - "token-macro:2.5"
    - "sse-gateway:1.16"
    - "pipeline-rest-api:2.10"
    - "workflow-durable-task-step:2.22"
    - "workflow-step-api:2.16"
    - "jenkins-design-language:1.8.4"
    - "github-api:1.92"
    - "workflow-basic-steps:2.11"
    - "junit:1.26.1"
    - "workflow-multibranch:2.20"
    - "pipeline-model-declarative-agent:1.1.1"
    - "blueocean-jwt:1.8.4"
    - "variant:1.1"
    - "github:1.29.3"
    - "jackson2-api:2.8.11.3"
    - "pipeline-model-api:1.3.2"
    - "workflow-api:2.30"
    - "handlebars:1.1.1"
    - "credentials:2.1.18"
    - "config-file-provider:3.2"
    - "htmlpublisher:1.17"
    - "pipeline-input-step:2.8"
    - "pipeline-milestone-step:1.3.1"
    - "blueocean-display-url:2.2.0"
    - "plain-credentials:1.4"
    - "kubernetes:1.12.6"
    - "bouncycastle-api:2.17"
    - "blueocean-jira:1.8.4"
    - "pipeline-stage-step:2.3"
    - "blueocean-events:1.8.4"
    - "blueocean-rest:1.8.4"
    - "workflow-support:2.21"
    - "authentication-tokens:1.3"
    - "pipeline-stage-view:2.10"
    - "jquery-detached:1.2.1"
    - "blueocean-rest-impl:1.8.4"
    - "docker-workflow:1.17"
    - "blueocean-dashboard:1.8.4"
    - "handy-uri-templates-2-api:2.1.6-1.0"
    - "kubernetes-credentials:0.4.0"
    - "github-branch-source:2.4.0"
    - "pubsub-light:1.12"
    - "git-server:1.7"
    - "blueocean-github-pipeline:1.8.4"
    - "display-url-api:2.2.0"
    - "cloudbees-folder:6.6"
    - "blueocean-personalization:1.8.4"
    - "blueocean-pipeline-api-impl:1.8.4"
    - "lockable-resources:2.3"
    - "jacoco:3.0.3"
    - "git-client:2.7.3"
    - "pipeline-graph-analysis:1.7"
    - "code-coverage-api:1.0.5"
    - "nodejs:1.2.6"
    - "git:3.9.1"
    - "blueocean-pipeline-editor:1.8.4"
    - "pipeline-build-step:2.7"
    - "blueocean-commons:1.8.4"
    - "matrix-project:1.13"
    - "blueocean-pipeline-scm-api:1.8.4"
    - "scm-api:2.2.8"
    - "blueocean:1.8.4"
    - "script-security:1.46"
    - "jira:3.0.2"
    - "branch-api:2.0.20"
    - "pipeline-model-extensions:1.3.2"
    - "structs:1.17"
    - "blueocean-git-pipeline:1.8.4"
    - "favorite:2.3.2"
    - "gradle:1.29"
    - "blueocean-web:1.8.4"
    - "workflow-cps:2.57"
    - "blueocean-config:1.8.4"
    - "workflow-aggregator:2.6"

agent:
  resources:
    requests:
      cpu: 2000m
      memory: 2048Mi
    limits:
      cpu: 8000m
      memory: 8192Mi

persistence:
  enabled: true
  existingClaim: jenkins
