compute:
  syncthing:
    cost: { type: Free }
    syncthing:
      description: A product for use in syncthing
      cpu: 1
      memory: 1
      gpu: 0
  cpu:
    cost: { type: Money }
    template:
      cpu: [1, 2, 200]
      memory: 1
      description: An example CPU machine with 1 vCPU.
      pricePerHour: 0.5
  cpu-h:
    cost:
      type: Resource
      interval: Minutely
    template:
      cpu: [1, 2]
      memory: 1
      description: An example CPU machine with 1 vCPU.
storage:
  storage:
    cost:
      type: Resource
      unit: GB
    storage:
      description: An example storage system
    share:
      description: This drive type is used for shares only.
    project-home:
      description: This drive type is used for member files of a project only.
publicLinks:
  public-link:
    cost: { type: Free }
    public-link:
      description: An example public link
publicIps:
  public-ip:
    cost:
      type: Resource
      unit: IP
    public-ip:
      description: A _fake_ public IP product
licenses:
  license:
    cost: { type: Resource }
    license:
      description: A _fake_ license
      tags: ["fake", "license"]