def initialize() {
  try {
    stage('build contact-book-service') {
      sh '''cd contact-book-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return currentBuild.result ?: 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'contact-book-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'contact-book-service-detekt-Report', reportTitles: ''])
  }
  try {
    stage('test contact-book-service') {
      sh '''cd contact-book-service
      ./gradlew test'''
    }
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}

return this
