#!/usr/bin/env python3
# File: /opt/ucloud/scripts/my-script

import sys
import json

with open(sys.argv[1]) as fp:
    request = json.load(fp)

response = { "output": request["ucloud"]["machine"]["name"] }
print(json.dumps(response))

