#!/usr/bin/env python3
import json
import sys
import os

with open(sys.argv[1]) as fp:
    request = json.load(fp)

path = request['path']
driveSize = 0

try:
    with open(os.path.join(path, "usage.txt"), 'r') as file:
        data = file.read().rstrip()
        driveSize = int(data)
except FileNotFoundError:
    pass

response = {
    'bytesUsed': int(driveSize)
}

print(json.dumps(response))
