application: v2

name: config-variable-injection
version: v1.32

software:
  type: Native

  build:
    type: Spack
    repository: MyRepository
    packages:
    - package

  load:
    type: Module
    modules:
    - package

invocation: >
  echo {{ cfg.myGreeting | default("hello world") }}
  echo {{ cfg.myVariable }} + {{ cfg.myOtherVariable }} = \
    {{ cfg.myVariable + cfg.myOtherVariable }}
  my-package
