application: v2

name: config-variable-injection
version: v1.32

software:
  type: Native

invocation: |
  echo {{ cfg.myGreeting | default("hello world") }}
  echo {{ cfg.myVariable }} + {{ cfg.myOtherVariable }} = \
    {{ cfg.myVariable + cfg.myOtherVariable }}
