def initialize() {

  try {
    stage('build indexing-service') {
      sh '''cd indexing-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'indexing-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'indexing-service-detekt-Report', reportTitles: ''])
  }
  try {
    stage('test indexing-service') {
      sh '''cd indexing-service
      ./gradlew test'''
    } 
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}

return this