def initialize() {

  try {
    stage('build activity-service') {
      sh '''cd activity-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'activity-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'activity-service-detekt-Report', reportTitles: ''])
  }

  try {
    stage('test activity-service') {
      sh '''cd activity-service
      ./gradlew test'''
    } 
  } catch (e) {
    echo "Test FAILED"
    return  'UNSTABLE'
  }
  return 'SUCCESS'
}

return this