#!/usr/bin/env bash
mkdir -p /etc/service/mservice/supervise
cat >/etc/service/mservice/run <<EOF
#!/usr/bin/env bash
/usr/bin/ucloud $@
EOF
chmod +x /etc/service/mservice/run

exec /usr/sbin/runit_bootstrap
tail -f /dev/null
