#!/usr/bin/env bash
cephfs_mount="/mnt/cephfs"
workspace_id=$1
workspace_dir="${cephfs_mount}/workspace/${workspace_id}"
merged_root=$2
directory_name=$3
real_path=$4
snapshot_path=$5

mkdir -p "${merged_root}/${directory_name}" &> /dev/null

#fuse-overlayfs -o "lowerdir=${cephfs_mount}/${snapshot_path},"\
#"upperdir=${workspace_dir}/snapshots/${directory_name}/upper,"\
#"workdir=${workspace_dir}/snapshots/${directory_name}/work" \
#"${merged_root}/${directory_name}"

tmp_work="/tmp/workspaces/${workspace_id}"
mkdir -p /tmp/workspaces/${workspace_id}/{upper,work}

mount -t overlay overlay -o "lowerdir=${cephfs_mount}/${snapshot_path},"\
"upperdir=${workspace_dir}/snapshots/${directory_name}/upper,"\
"workdir=${workspace_dir}/snapshots/${directory_name}/work" \
"${merged_root}/${directory_name}"

#"upperdir=${tmp_work}/upper,"\
#"workdir=${tmp_work}/work" \
