from alpine:latest
run mkdir -p /opt/cow/.bin
copy cow /opt/cow/cow
copy cowmount /opt/cow/.bin/cowmount
copy fuse-overlayfs /opt/cow/.bin/fuse-overlayfs
copy jq /opt/cow/.bin/jq
copy install.sh /opt/cow/install.sh
