package migrations

import (
	"ucloud.dk/shared/pkg/audit"
	db "ucloud.dk/shared/pkg/database"
)

func Init() {
	// Changes must always be appended to the END of this function
	db.AddMigration(genericLicensesV1())
	db.AddMigration(connectionsV1())
	db.AddMigration(apmEventsV1())
	db.AddMigration(slurmV1())
	db.AddMigration(connectionsV2())
	db.AddMigration(jobDatabaseV1())
	db.AddMigration(jobDatabaseV2())
	db.AddMigration(driveDatabaseV1())
	db.AddMigration(scriptLogV1())
	db.AddMigration(slurmV2())
	db.AddMigration(fileTransfersV1())
	db.AddMigration(uploadsV1())
	db.AddMigration(slurmV3())
	db.AddMigration(k8sV1())
	db.AddMigration(apmEventsV2())
	db.AddMigration(ipDatabaseV1())
	db.AddMigration(driveDatabaseV2())
	db.AddMigration(integratedAppsV1())
	db.AddMigration(connectionsV3())
	db.AddMigration(driveDatabaseV3())
	db.AddMigration(ingressDatabaseV1())
	db.AddMigration(licenseDatabaseV1())
	db.AddMigration(jobDatabaseV3())
	db.AddMigration(ipDatabaseV2())
	db.AddMigration(inferenceV1())
	db.AddMigration(audit.MigrationV1())
	db.AddMigration(audit.MigrationV2())
	db.AddMigration(kubevirtV1())
	db.AddMigration(privateNetworkDatabaseV1())
	db.AddMigration(k8sV2())
	db.AddMigration(inferenceV2())
	db.AddMigration(apmEventsV3())
	db.AddMigration(inferenceV3())
	db.AddMigration(inferenceV4())
	db.AddMigration(inferenceV5())
	db.AddMigration(inferenceV6())
	db.AddMigration(inferenceV7())
	db.AddMigration(inferenceV8())
	db.AddMigration(inferenceV9())
	db.AddMigration(inferenceV10())
	db.AddMigration(inferenceV11())
	db.AddMigration(inferenceV12())
	db.AddMigration(inferenceV13())
	db.AddMigration(inferenceV14())
	db.AddMigration(inferenceV15())
	db.AddMigration(ucxDeliveryV1())
	db.AddMigration(kubevirtV2())
}
