def initialize() {

  stage('build client-core') {
    sh '''cd client-core
    ./gradlew clean
    ./gradlew build -x test'''
  }

  try {
    stage('test client-core') {
      sh '''cd client-core
      ./gradlew test'''
    } 
  } catch (e) {
      echo "Test FAILED"
  } finally {
    junit '**/client-core/build/test-results/**/*.xml'      
    def currentResult = currentBuild.result ?: 'SUCCESS'
    return currentResult
  }
}

return this