def initialize() {

  try {
    stage('build client-core') {
      sh '''cd client-core
      ./gradlew clean
      ./gradlew build -x test
      ./gradlew detekt'''
    }
  } catch (e) {
    echo "Build Failed"
    return currentBuild.result ?: 'FAILURE'
  } finally {
    publishHTML([allowmissing: false , alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'client-core/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'client-core-detekt-Report', reportTitles: ''])
  }

  try {
    stage('test client-core') {
      sh '''cd client-core
      ./gradlew test'''
    } 
  } catch (e) {
    echo "Test FAILED"
    return currentBuild.result ?: 'UNSTABLE'
  }
  return currentBuild.result ?: 'SUCCESS'
}

return this