def initialize() {

  try {
    stage('build alerting-service') {
      sh '''cd alerting-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'alerting-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'alerting-service-detekt-Report', reportTitles: ''])
  }
  return 'SUCCESS'
}

return this
