#!/usr/bin/env bash
docker volume create ucloud_im_konan
docker volume create ucloud_im_gradle
docker volume create ucloud_im_data
docker build --target development -t ucloud-im-dev .
docker run \
  -e "GITHUB_USERNAME=${GITHUB_USERNAME}" \
  -e "GITHUB_TOKEN=${GITHUB_TOKEN}" \
  -d --rm -it \
  -v $PWD:/opt/ucloud \
  -v ucloud_im_konan:/root/.konan \
  -v ucloud_im_gradle:/root/.gradle \
  -v ucloud_im_data:/etc/ucloud \
  --name ucloud-im-dev \
  ucloud-im-dev \
  bash -c "echo export GITHUB_USERNAME=$GITHUB_USERNAME >> /root/.bashrc; echo export GITHUB_TOKEN=$GITHUB_TOKEN >> /root/.bashrc ; tail -f /dev/null"
echo "Development environment has been started."
echo "Connect with: 'dev_connect'"
