def initialize() {

	try {
	  stage('build storage-service') {
	    sh '''cd storage-service
	    ./gradlew clean
	    ./gradlew build -x test'''
	  }
	} catch (e) {
    echo "Build Failed"
    return currentBuild.result ?: 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'storage-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'storage-service-detekt-Report', reportTitles: ''])
  }
}	

return this