def initialize() {

  stage('build auth-service') {
    sh '''cd auth-service
    ./gradlew clean
    ./gradlew build -x test'''
  }

  try {
    stage('test auth-service') {
      sh '''cd auth-service
      ./gradlew test'''
    } 
  } catch (e) {
      echo "Test FAILED"
  } finally {
    junit '**/auth-service/build/test-results/**/*.xml'      
    def currentResult = currentBuild.result ?: 'SUCCESS'
    return currentResult
    
  }
}

return this