def initialize() {

  try {
    stage('build auth-service') {
      sh '''cd auth-service
        ./gradlew clean
        ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'auth-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'auth-service-detekt-Report', reportTitles: ''])
  }

  try {
    stage('test auth-service') {
      sh '''cd auth-service
          ./gradlew test'''
    }
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}

return this