def initialize() {
    try {
        stage('Build and Test') {
            container('node') {
                sh '''cd frontend-web/webclient
                    npm install
                    npm run test
                '''
            }
        }
    } catch (e) {
        echo "Build Failed"
        return currentBuild.result ?: 'FAILURE'
    } finally {
        step([$class: 'CoberturaPublisher', coberturaReportFile: 'frontend-web/webclient/coverage/cobertura-coverage.xml'])
    }

    return currentBuild.result ?: 'SUCCESS'

}

return this
