def initialize() {

  stage('build indexing-service') {
    sh '''cd indexing-service
    ./gradlew clean
    ./gradlew build -x test'''
  }

  try {
    stage('test indexing-service') {
      sh '''cd indexing-service
      ./gradlew test'''
    } 
  } catch (e) {
      echo "Test FAILED"
  } finally {
    junit '**/indexing-service/build/test-results/**/*.xml'      
    def currentResult = currentBuild.result ?: 'SUCCESS'
    return currentResult
  }
}

return this