#!/usr/bin/env python3
import json
import sys
import subprocess
import os
import re

"""
This example extension maps UCloud projects into a series of local UNIX groups.

As with any other example extension, it is important to remember that they should be tailored to the needs of a
specific system. These are owned and maintained by the operators of the system on which the integration module runs.

Every project is mapped into a UNIX group and every group is mapped into an additional UNIX group. Members are 
automatically synchronized to these groups. However, this synchronization only occurs if the users have already
performed a connection with this provider (i.e. a UID mapping exists).

The following diagram shows an example of how the mapping is performed:

+---------------------------------------+               +---------------------------------------+ 
|                                       |               |                                       |
| Title: My Research                    |               | UNIX group: my_research_42410         |
|                                       |               |                                       |
| Group: Ph.D. Students                 |    maps to    | UNIX group: ph_d__students_42450      |
| Group: All                            | <===========> | UNIX group: all_42451                 |
| Group: Taskforce Foobar               |               | UNIX group: taskforce_foobar_42470    |
|                                       |               |                                       |
+---------------------------------------+               +---------------------------------------+

If a project/group is renamed, then the corresponding UNIX group is also renamed. However, the GID of the UNIX group
itself is retained.

The local unix groups are created using the following commands, which are all wrapped in utility functions as seen
below:

- /usr/sbin/groupadd
- /usr/sbin/groupmod
- /usr/sbin/groupdel
- /usr/sbin/usermod
- /usr/bin/gpasswd
- /usr/bin/getent

If these functions are not available on your target system, or they are simply unsuitable for group management, then you
should attempt to change the functions below to more suitable for your system.
"""

# NOTE(Dan): This script requires root privileges. However, the integration module will launch it with the privileges
# of the ucloud service user. As a result, we immediately attempt to elevate our own privileges via `sudo`.
if os.getuid() != 0:
    res = subprocess.run(['sudo', '-S', sys.argv[0], sys.argv[1]], stdin=open('/dev/null'))
    if res.returncode != 0:
        print("project-extension failed. Is sudo misconfigured?")
        exit(1)
    exit(0)

########################################################################################################################

request = json.loads(open(sys.argv[1]).read())
request_type = request['type']

########################################################################################################################

def generate_name(ucloud_title, allocated_gid):
    return re.sub(r'[^a-z0-9]', '_', ucloud_title.lower()) + '_' + str(allocated_gid)

def create_group(gid, name):
    result = subprocess.run(['/usr/sbin/groupadd', '-g', str(gid), name], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return result.returncode == 0

def rename_group(gid, name):
    result = subprocess.run(['/usr/sbin/groupmod', '-n', name, get_group_by_gid(gid)], stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE)
    return result.returncode == 0

def delete_group(gid):
    group_name = get_group_by_gid(gid)
    if group_name is None:
        return False
    result = subprocess.run(['/usr/sbin/groupdel', get_group_by_gid(gid)], stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE)
    return result.returncode == 0

def add_user_to_group(uid, gid):
    if get_group_by_gid(gid) is None:
        print("{} warning: Non-existing group with id {}".format(request_type,gid))

    if get_username_by_uid(uid) is None:
        print("{} warning: Non-existing user with id {}".format(request_type,uid))
        exit(0)

    result = subprocess.run(['/usr/sbin/usermod', '-a', '-G', get_group_by_gid(gid), get_username_by_uid(uid)],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return result.returncode == 0

def remove_user_from_group(uid, gid):
    result = subprocess.run(['/usr/bin/gpasswd', '-d', get_username_by_uid(uid), get_group_by_gid(gid)],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return result.returncode == 0

def get_gid_by_group(group_name):
    result = subprocess.run(['/usr/bin/getent', 'group', group_name], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        return None
    return int(result.stdout.decode('UTF-8').split(':')[2])

def get_group_by_gid(gid):
    result = subprocess.run(['/usr/bin/getent', 'group', str(gid)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        return None
    return result.stdout.decode('UTF-8').split(':')[0]

def get_username_by_uid(uid):
    result = subprocess.run(['/usr/bin/getent', 'passwd', str(uid)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        return None
    return result.stdout.decode('UTF-8').split(':')[0]

########################################################################################################################

if request_type == 'project_renamed':
    gid = request['newProject']['localId']
    if request['oldProject'] is None:
        create_group(gid, generate_name(request['newTitle'], gid))
    else:
        rename_group(gid, generate_name(request['newTitle'], gid))

elif request_type == 'group_created':
    for group in request['groups']:
        gid = group['localId']
        create_group(gid, generate_name(group['group']['specification']['title'], gid))

elif request_type == 'group_deleted':
    for group in request['groups']:
        delete_group(group['localId'])

elif request_type == 'group_renamed':
    gid = request['group']['localId']
    rename_group(gid, generate_name(request['group']['group']['specification']['title'], gid))

elif request_type == 'members_added_to_project':
    gid = request['newProject']['localId']
    create_group(gid, generate_name(request['newProject']['project']['specification']['title'], gid))
    for member in request['newMembers']:
        uid = member['uid']
        if uid is None: continue
        add_user_to_group(uid, gid)

elif request_type == 'members_removed_from_project':
    gid = request['newProject']['localId']
    create_group(gid, generate_name(request['newProject']['project']['specification']['title'], gid))
    for member in request['removedMembers']:
        uid = member['uid']
        if uid is None: continue
        remove_user_from_group(uid, gid)

elif request_type == 'members_added_to_group':
    gid = request['group']['localId']
    for member in request['newMembers']:
        uid = member['uid']
        if uid is None: continue
        add_user_to_group(uid, gid)

elif request_type == 'members_remove_from_group':
    gid = request['group']['localId']
    for member in request['removedMembers']:
        uid = member['uid']
        if uid is None: continue
        remove_user_from_group(uid, gid)

print('{}')
