#!/usr/bin/env python3
import json
import sys
import os

request = json.loads(open(sys.argv[1]).read())

driveSize = (os.popen("du -sb --exclude='.ucloud-tasks' " + request['path']).read().split('\t'))[0]

response = {
    'bytesUsed': int(driveSize)
}

print(json.dumps(response))
