def initialize() {

  try {
    stage('build metadata-service') {
      sh '''cd metadata-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'metadata-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'metadata-service-detekt-Report', reportTitles: ''])
  }

  try {
    stage('test metadata-service') {
      sh '''cd metadata-service
      ./gradlew test'''
    } 
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}

return this