version: "3.9"
services:
  redis:
    image: redis:5.0.9
    volumes:
      - redisData:/data
    hostname: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    volumes:
      - elasticData:/usr/share/elasticsearch/data
    ports:
    - ${ELASTIC_PORT:-9200}:9200
    hostname: elasticsearch

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ${PWD}/.compose/postgres:/var/lib/postgresql/data
      - ${PWD}/backend:/opt/ucloud
    ports:
    - ${POSTGRES_PORT:-35432}:5432
    hostname: postgres

  k3s:
    image: rancher/k3s:v1.21.6-rc2-k3s1
    privileged: true
    tmpfs:
      - /run
      - /var/run
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
    - ucloudFiles:/mnt/cephfs
    - /tmp:/tmp
    - k3sConfig:/output
    - k3sData:/var/lib/rancher/k3s
    - k3sCni:/var/lib/cni
    - k3sKubelet:/var/lib/kubelet
    - k3sEtc:/etc/rancher
    ports:
    - ${K3S_PORT:-6443}:6443
    command:
      - server
    hostname: k3s

  syncthing:
    image: syncthing/syncthing:1.17
    user: root
    hostname: syncthing
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - syncthingConfig:/var/syncthing
      - ucloudFiles:/mnt/cephfs
      - type: bind
        source: ${PWD}/syncfiles
        target: /mnt/sync
        bind:
          propagation: slave
    ports:
      - 8485:8384
      - 22001:22001/tcp
      - 22001:22001/udp
    restart: unless-stopped

  backend:
    image: dreg.cloud.sdu.dk/ucloud/ucloud:2021.3.0-alpha1
    user: root
    command:
      - /opt/service/bin/service
      - --dev
      - --config-dir
      - /etc/ucloud
    volumes:
      - ucloudData:/etc/ucloud
      - ucloudFiles:/mnt/cephfs
      - k3sConfig:/mnt/k3s
      - type: bind
        source: ${PWD}/syncfiles
        target: /mnt/sync
        bind:
          propagation: shared
      - syncthingConfig:/mnt/syncthing
    ports:
      - ${BACKEND_PORT:-8080}:8080
    restart: always
    depends_on:
      - redis
      - postgres
      - elasticsearch
      - k3s
      - syncthing
      - keycloak
    hostname: backend

  frontend:
    image: dreg.cloud.sdu.dk/ucloud/webclient:0.51.0-alpha4
    hostname: frontend

