package dk.sdu.cloud.sql.migrations

import dk.sdu.cloud.sql.MigrationHandler

fun loadMigrations(migrationHandler: MigrationHandler) {
    // NOTE(Dan): Do not re-order these. You should always add new migrations at the bottom of this function.
    migrationHandler.addScript(V1__TicketConnector())
    migrationHandler.addScript(V1__JobMapping())
    migrationHandler.addScript(V2__UserMapping())
    migrationHandler.addScript(V1__FileDownloadSessions())
    migrationHandler.addScript(V1__FileUploadSessions())
    migrationHandler.addScript(V1__Tasks())
    migrationHandler.addScript(V1__ProjectMapping())
    migrationHandler.addScript(V1__SimpleProjectPluginInitial())
    migrationHandler.addScript(V2__SimpleProjectPlugin())
    migrationHandler.addScript(V2__SessionMapping())
    migrationHandler.addScript(V3__SlurmAccountMapper())
    migrationHandler.addScript(V4__SlurmAccounting())
    migrationHandler.addScript(V5__FixSlurmAccountMapper())
    migrationHandler.addScript(V1__MessageSigning())
    migrationHandler.addScript(V1__Puhuri())
    migrationHandler.addScript(V1__UCloudStorage())
    migrationHandler.addScript(V1__UCloudCompute())
    migrationHandler.addScript(V1__ComputeSessions())
    migrationHandler.addScript(V2__ComputeSessions())
    migrationHandler.addScript(V1__GenericLicenses())
    migrationHandler.addScript(V2__UCloudCompute())
    migrationHandler.addScript(V2__Puhuri())
    migrationHandler.addScript(V1__PosixStorage())
    migrationHandler.addScript(V1__ExtensionLog())
    migrationHandler.addScript(V1__Events())
    migrationHandler.addScript(V1__Maintenance())
    migrationHandler.addScript(V2__UCloudStorage())
    migrationHandler.addScript(V3__UCloudStorage())
    migrationHandler.addScript(V1__Accounting())
    migrationHandler.addScript(V1__ActivitySystem())
    migrationHandler.addScript(V4__UCloudStorage())
    migrationHandler.addScript(V3__UCloudCompute())
    migrationHandler.addScript(V2__GenericLicenses())
    migrationHandler.addScript(V2__Events())
}
