def initialize() {

  stage('build service-common') {
    sh '''cd service-common
    ./gradlew clean
    ./gradlew build -x test'''
  }

  try {
    stage('test service-common') {
      sh '''cd service-common
      ./gradlew test'''
    } 
  } catch (e) {
      echo "Test FAILED"
  } finally {
    junit '**/service-common/build/test-results/**/*.xml'      
    def currentResult = currentBuild.result ?: 'SUCCESS'
    return currentResult
  }
}

return this