def initialize() {

  try {
    stage('build service-common') {
      sh '''cd service-common
      ./gradlew clean
      ./gradlew build -x test
      ./gradlew detekt'''
    }
  } catch (e) {
    echo "Build Failed"
    return 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'service-common/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'service-common-detekt-Report', reportTitles: ''])
  }

  try {
    stage('test service-common') {
      sh '''cd service-common
      ./gradlew test'''
    } 
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}

return this