def initialize() {
  try {
    stage('build app-kubernetes-service') {
      sh '''cd app-kubernetes-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return currentBuild.result ?: 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: '{{ serviceName }}-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: '{{ serviceName }}-service-detekt-Report', reportTitles: ''])
  }
  try {
    stage('test app-kubernetes-service') {
      sh '''cd app-kubernetes-service
      ./gradlew test'''
    }
  } catch (e) {
    echo "Test FAILED"
    return currentBuild.result ?: 'UNSTABLE'
  }
  return currentBuild.result ?: 'SUCCESS'
}

return this
