providerId: slurm
launchRealUserInstances: true
allowRootMode: false
developmentMode: true
disableInsecureFileCheckIUnderstandThatThisIsABadIdeaButSomeDevEnvironmentsAreBuggy: true
hosts:
  ucloud:
    host: backend
    scheme: http
    port: 8080
  self:
    host: slurm.localhost.direct
    scheme: https
    port: 443
cors:
  allowHosts: ["ucloud.localhost.direct"]