compute:
  cpu:
    allowSubAllocations: false
    cost:
      type: Resource
      interval: Minutely
      unit: Cpu
    template:
      cpu: [1, 2, 200]
      memory: 1
      description: An example CPU machine with 1 vCPU.
storage:
  storage:
    allowSubAllocations: false
    cost:
      type: Resource
      unit: GB
    storage:
      description: An example storage system