// Vendor styles
// -----------------------
import "uppy/src/scss/uppy.scss";
import "Navigation/Sidebar.scss";
import "Files/Files.scss";
import "loaders.css/loaders.css";
import "LoadingIcon/colors.scss";
import "semantic-ui-css/semantic.min.css";
import "Applications/wizard.scss";
import "Applications/Applications.scss";
import "Breadcrumbs/Breadcrumbs.scss";
import "Dashboard/dashboard.scss";
import "react-datepicker/dist/react-datepicker.css";
import "Files/Files.scss";
import "Styling/Shared.scss";
import "Metadata/view.scss";
import "Navigation/Header.scss";
import "Notifications/index.scss";
import "Pagination/pagination.scss";
import "Shares/List.scss";
import "Uploader/index.scss";
import "Zenodo/Zenodo.scss";
import "UserSettings/2fa.scss";