#!/usr/bin/env bash
set -e
set -x

version_string=`grep "version '.*'" build.gradle`
version=`python -c "
import sys 
v = sys.argv[1] 
v_dash = v.index(\"-\") if \"-\" in v else len(v) - 1

print(v[v.index(\"'\") + 1:v_dash])
" "${version_string}"`

name=`grep "rootProject" settings.gradle | cut -c 21- | rev | cut -f 2 -d "'" | rev`
echo "Tagging as ${name}:${version}"

rm -rf build/distributions
rm -rf build/service
gradle distTar
(mkdir -p build/service || true)
cp build/distributions/*.tar build/service.tar
cd build/service
tar xvf ../service.tar --strip-components=1 && \
cd ../../
mv build/service/bin/${name} build/service/bin/service 

docker build \
    -t "${name}:${version}" \
    -f Dockerfile.local \
    .

if hash docker-publish; then
    docker-publish "${name}:${version}"
fi
