#!/usr/bin/env bash
set -e
set -x

gradle generateBuildConfig
name=`cat src/generated/resources/name.txt`
version=`cat src/generated/resources/version.txt`
echo "Tagging as ${name}:${version}"

rm -rf build/distributions
rm -rf build/service
gradle distTar
(mkdir -p build/service || true)
cp build/distributions/*.tar build/service.tar
cd build/service
tar xvf ../service.tar --strip-components=1 && \
cd ../../
mv build/service/bin/${name} build/service/bin/service 

docker build \
    -t "${name}:${version}" \
    -f Dockerfile \
    .

if hash docker-publish; then
    docker-publish "${name}:${version}"
fi
