#!/usr/bin/env bash

if test "$#" -lt 1; then
    echo "Usage: copy_docs <docs_repo>"
    echo "This script should be run from the root of SDUCloud"
    exit 1
fi

set -x
target_dir=$1
current_dir=`pwd`

for service_name in *-service; do
    mkdir -p "${target_dir}/${service_name}"
    cp "${service_name}/README.md" "${target_dir}/${service_name}/README.md"
    cp -r "${service_name}/wiki" "${target_dir}/${service_name}/wiki"
done


mkdir -p "${target_dir}/infrastructure"
cp "infrastructure/README.md" "${target_dir}/infrastructure/README.md"
cp -r "infrastructure/wiki" "${target_dir}/infrastructure/wiki"

mkdir -p "${target_dir}/service-common"
cp "service-common/README.md" "${target_dir}/service-common/README.md"
cp -r "service-common/wiki" "${target_dir}/service-common/wiki"

cp README.md "${target_dir}/README.md"

cd $target_dir
git add -A :/
git commit -m "Synchronized repository at $(date)"
git push

cd $current_dir