package foundation

import _ "embed"

// Generated by mailtpl/generate.sh. Please run the script from the mailtpl folder.

//go:embed mailtpl/accounting/low_resources.j2
var tplAccountingLowResources []byte

//go:embed mailtpl/accounting/low_resources_reminder.j2
var tplAccountingLowResourcesReminder []byte

//go:embed mailtpl/grants/transfer.j2
var tplGrantsTransfer []byte

//go:embed mailtpl/grants/updated_to_applicant.j2
var tplGrantsUpdatedToApplicant []byte

//go:embed mailtpl/grants/new_application.j2
var tplGrantsNewApplication []byte

//go:embed mailtpl/grants/approved_to_applicant.j2
var tplGrantsApprovedToApplicant []byte

//go:embed mailtpl/grants/rejected_to_applicant.j2
var tplGrantsRejectedToApplicant []byte

//go:embed mailtpl/grants/comment.j2
var tplGrantsComment []byte

//go:embed mailtpl/base.j2
var tplBase []byte

//go:embed mailtpl/auth/verify.j2
var tplAuthVerify []byte

//go:embed mailtpl/auth/reset.j2
var tplAuthReset []byte

//go:embed mailtpl/projects/invitation.j2
var tplProjectsInvitation []byte

//go:embed mailtpl/projects/user_removed_to_user.j2
var tplProjectsUserRemovedToUser []byte

//go:embed mailtpl/projects/user_left.j2
var tplProjectsUserLeft []byte

//go:embed mailtpl/projects/user_removed_to_admin.j2
var tplProjectsUserRemovedToAdmin []byte

//go:embed mailtpl/projects/role_change.j2
var tplProjectsRoleChange []byte

//go:embed mailtpl/base_support.j2
var tplBaseSupport []byte

//go:embed mailtpl/support/support.j2
var tplSupportSupport []byte

//go:embed mailtpl/jobs/events.j2
var tplJobsEvents []byte
