package foundation

import _ "embed"

// Generated by mailtpl/generate.sh. Please run the script from the mailtpl folder.

//go:embed policies/restrict_applications.yaml
var restrictApplications []byte

//go:embed policies/restrict_cut_and_paste.yaml
var restrictCutAndPast []byte

//go:embed policies/restrict_downloads.yaml
var restrictDownloads []byte

//go:embed policies/restrict_integrated_applications.yaml
var restrictIntegratedApplications []byte

//go:embed policies/restrict_internet_access.yaml
var restrictInternetAccess []byte

//go:embed policies/restrict_organizations_members.yaml
var restrictOrganizationsMembers []byte

//go:embed policies/restrict_provider_file_transfers.yaml
var restrictProviderTransfers []byte

//go:embed policies/restrict_public_ips.yaml
var restrictPublicIPs []byte

//go:embed policies/restrict_public_links.yaml
var restrictPublicLinks []byte

//go:embed policies/restrict_source_ip_range.yaml
var restrictSourceIpRange []byte

type LoadedPolicy struct {
	PolicyName string
	Bytes      []byte
}

func pullProjectPolicies() []LoadedPolicy {
	policies := []LoadedPolicy{
		{
			PolicyName: "restrictApplications",
			Bytes:      restrictApplications,
		},
		{
			PolicyName: "restrictCutAndPast",
			Bytes:      restrictCutAndPast,
		}, {
			PolicyName: "restrictDownloads",
			Bytes:      restrictDownloads,
		}, {
			PolicyName: "restrictIntegratedApplications",
			Bytes:      restrictIntegratedApplications,
		}, {
			PolicyName: "restrictInternetAccess",
			Bytes:      restrictInternetAccess,
		}, {
			PolicyName: "restrictOrganizationsMembers",
			Bytes:      restrictOrganizationsMembers,
		}, {
			PolicyName: "restrictProviderTransfers",
			Bytes:      restrictProviderTransfers,
		}, {
			PolicyName: "restrictPublicIPs",
			Bytes:      restrictPublicIPs,
		}, {
			PolicyName: "restrictPublicLinks",
			Bytes:      restrictPublicLinks,
		}, {
			PolicyName: "restrictSourceIpRange",
			Bytes:      restrictSourceIpRange,
		},
	}
	return policies
}
