refreshToken: "%s"
tokenValidation:
  sharedSecret: "%s"
selfAddress:
  address: localhost
  port: 8080
  scheme: http
selfPublic:
  address: ucloud.localhost.direct
  port: 443
  scheme: https
database:
  username: postgres
  password: postgrespassword
  database: postgres
  ssl: false
  host:
    address: postgres
    port: 5432
logs:
  directory: /var/log/ucloud
  rotation:
    enabled: true
    retentionPeriodInDays: 7
emails:
  enabled: false

branding:
  deploymentName: "UCloud Production"

  dataProtection:
    title: "SDU Data Protection"
    href: "https://www.sdu.dk/en/om_dette_websted/databeskyttelse"

  statusPage:
    title: "Site status"
    href: "https://status.cloud.sdu.dk"

  documentation:
    title: "Docs"
    href: "https://docs.cloud.sdu.dk/"

  supportEmail: "support@escience.sdu.dk"
  faqLink: "https://docs.cloud.sdu.dk/help/faq.html"

  loginPage:
    type: 0
    primaryLogoImage: "no-logo.png"
    secondaryLogoImages:
      - "no-secondary-logo.png"