def initialize() {
  try {
    stage('build redis-cleaner-service') {
      sh '''cd redis-cleaner-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return currentBuild.result ?: 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'redis-cleaner-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'redis-cleaner-service-detekt-Report', reportTitles: ''])
  }
  try {
    stage('test redis-cleaner-service') {
      sh '''cd redis-cleaner-service
      ./gradlew test'''
    }
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}

return this
