#!/usr/bin/env bash
set -e
set -x

name=syncthing
rm -rf build/distributions
rm -rf build/service
gradle distTar
(mkdir -p build/service || true)
cp build/distributions/*.tar build/service.tar
cd build/service
tar xvf ../service.tar --strip-components=1 && \
cd ../../
mv build/service/bin/${name} build/service/bin/service 

docker build \
    -t "${name}" \
    -f Dockerfile \
    .

