def initialize() {

  stage('build ABC2-sync') {
    sh '''cd abc2-sync
    ./gradlew clean
    ./gradlew build -x test'''
  }

  try {
    stage('test ABC2-sync') {
      sh '''cd abc2-sync
      ./gradlew test'''
    } 
  } catch (e) {
      echo "Test FAILED"
  } finally {
    junit '**/abc2-sync/build/test-results/**/*.xml'      
    def currentResult = currentBuild.result ?: 'SUCCESS'
    if (currentResult == 'UNSTABLE') {
      echo "Build is unstable"
    }
    if (currentResult == 'SUCCESS') {
      jacoco  execPattern: '**/**.exec',
              exclusionPattern: '**/abc2-sync/src/test/**/*.class,**/AuthMockingKt.class,**/DatabaseSetupKt.class', 
              sourcePattern: '**/abc2-sync/src/main/kotlin/**'   
    }
  }
}

return this