def initialize() {
  
  try {
    stage('build ABC2-sync') {
      sh '''cd abc2-sync
      ./gradlew clean
      ./gradlew build -x test
      ./gradlew detekt'''
    }
  } catch (e) {
    echo "Build Failed"
    return currentBuild.result ?: 'FAILURE'
  } finally {
    publishHTML([allowmissing: false , alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'abc2-sync/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'abc2-sync-detekt-Report', reportTitles: ''])
  }
  
  try {
    stage('test ABC2-sync') {
      sh '''cd abc2-sync
      ./gradlew test'''
    } 
  } catch (e) {
    echo "Test FAILED"
    return currentBuild.result ?: 'UNSTABLE'
  }
  return currentBuild.result ?: 'SUCCESS'
}

return this