def initialize() {

  stage('build ABC2-sync') {
    sh '''cd abc2-sync
    ./gradlew clean
    ./gradlew build -x test'''
  }

  try {
    stage('test ABC2-sync') {
      sh '''cd abc2-sync
      ./gradlew test'''
    } 
  } catch (e) {
      echo "Test FAILED"
  } finally {
    junit '**/abc2-sync/build/test-results/**/*.xml'      
    def currentResult = currentBuild.result ?: 'SUCCESS'
    return currentResult
  }
}

return this