#!/usr/bin/env bash
echo "Using Gradle passwords from ~/.gradle/esci.properties"
version_string=`grep "version '.*'" build.gradle`
version=`python -c "
import sys 
v = sys.argv[1] 
v_dash = v.index(\"-\") if \"-\" in v else len(v) - 1

print(v[v.index(\"'\") + 1:v_dash])
" "${version_string}"`

name=`grep "rootProject" settings.gradle | cut -c 21- | rev | cut -f 2 -d "'" | rev`
echo "Tagging as ${name}:${version}"

rm -rf shared-gradle
cp -r ../shared-gradle shared-gradle

docker build \
    --target production \
    --build-arg GRADLE_PROPS="`cat ~/.gradle/esci.properties`" \
    --build-arg SERVICE_NAME="${name}" \
    -t "${name}:${version}" \
    .

rm -rf shared-gradle
