def initialize() {

  try {
    stage('build app-abacus-service') {
      sh '''cd app-abacus-service
      ./gradlew clean
      ./gradlew build -x test'''
    }
  } catch (e) {
    echo "Build Failed"
    return 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'app-abacus-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'metadata-service-detekt-Report', reportTitles: ''])
  }

  try {
    stage('test app-abacus-service') {
      sh '''cd app-abacus-service
      ./gradlew test'''
    }
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }

  return 'SUCCESS'
  
}

return this
