{
 "title": "Memory, Disk and CPU Usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM Usage (Services)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_name!=\"POD\", pod_name!=\"\", pod_name!~\".*scan.*|ambassador.*|registry.*|archiva.*\" , namespace=\"default\"}) by (pod_name) "
    }
   ]
  },
  {
   "title": "RAM Usage (All pods)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_name!=\"POD\", pod_name!=\"\"}) by (pod_name) "
    }
   ]
  },
  {
   "title": "Pod CPU usage in sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name!=\"\"}[5m])) by (pod_name)"
    }
   ]
  },
  {
   "title": "Pod Swap Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{container_name!=\"POD\", pod_name!=\"\"}) by (pod_name) "
    }
   ]
  },
  {
   "title": "Available space remaining in pvcs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}