{
 "title": "Request Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Average Response Time (All Requests)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "responseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "-requestName:files.upload.* && -requestName:app.*.submitFile* && -requestName:files.download && -requestName:files.simpleUpload.* && -requestName:files.workspace.* && -requestName:hpc.jobs.followWS && -requestName:app.compute.kubernetes.followWSStream && -requestName:app.compute.kubernetes.cancelWSStream",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User Generated Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "token.principal.username.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "-token.principal.username.keyword:_*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Service Generated Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "token.principal.username.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "token.principal.username.keyword:_*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Percentage of Requests with OK",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "alias": "ok",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "responseCode:[100 TO 399]",
     "timeField": "@timestamp"
    },
    {
     "alias": "all",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests with Failures",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requestName.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "-responseCode:[100 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "requestName.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "responseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "responseTime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "field": "responseTime",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "jobId.keyword",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "-files.upload.* && -app.*.submitFile && -files.download && -hpc.jobs.followWS && -app.compute.kubernetes.followWSStream && -app.compute.kubernetes.cancelWSStream",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}