{
 "title": "SDUCloud",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Number of User Request in Period",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "-token.principal.role:SERVICE && -requestName:\"auth.logout\" && -requestName:\"auth.refresh\" &&  -requestName:\"auth.webRefresh\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "graph",
   "description": "Measured in Requests",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "-token.principal.role:SERVICE && token.principal.username:\"?.*\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "token.principal.username.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": " token.principal.username ",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "-token.principal.role:SERVICE && token.principal.username:\"?.*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Users Signed Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from \"auth\".\"principals\""
    }
   ]
  },
  {
   "title": "Current Number of Shares",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "Select count(*) from \"share\".\"shares\""
    }
   ]
  },
  {
   "title": "Total Number of Favorite Files",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(*) from \"file_favorite\".\"favorites\""
    }
   ]
  },
  {
   "title": "Active Users in Period",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "token.principal.username.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "token.principal.username.keyword",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "-token.principal.role:SERVICE && token.principal.username:\"?.*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data Stored",
   "type": "graph",
   "description": "Updates every 3 hours\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval,previous),\n  sum(usage) AS \"usage\"\nFROM \"accounting_storage\".\"storage_usage_for_user\"\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 20 Most Active Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "token.principal.username.keyword",
       "id": "4",
       "settings": { "min_doc_count": 20, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "-token.principal.role:SERVICE && token.principal.username:\"?.*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Number of Jobs Started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) from \"app_orchestrator\".\"job_information\""
    }
   ]
  },
  {
   "title": "Total Compute Time Used",
   "type": "singlestat",
   "description": "Duration of job * number of nodes used for job",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 16 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select sum(duration_in_ms * nodes) from \"accounting_compute\".\"job_completed_events\""
    }
   ]
  },
  {
   "title": "Number of Apps Installed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count (A.name)\n            from \"app_store\".\"applications\" as A where (A.created_at) in (\n                select max(created_at)\n                from \"app_store\".\"applications\" as B\n                where A.name = B.name\n                group by name\n            )"
    }
   ]
  }
 ]
}