// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: gifts.proto

package grants

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrowseGiftsRequest_Type int32

const (
	BrowseGiftsRequest_TYPE_UNSPECIFIED         BrowseGiftsRequest_Type = 0
	BrowseGiftsRequest_TYPE_AVAILABLE_FOR_CLAIM BrowseGiftsRequest_Type = 1
	BrowseGiftsRequest_TYPE_OWNED_BY_MY_PROJECT BrowseGiftsRequest_Type = 2
)

// Enum value maps for BrowseGiftsRequest_Type.
var (
	BrowseGiftsRequest_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_AVAILABLE_FOR_CLAIM",
		2: "TYPE_OWNED_BY_MY_PROJECT",
	}
	BrowseGiftsRequest_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":         0,
		"TYPE_AVAILABLE_FOR_CLAIM": 1,
		"TYPE_OWNED_BY_MY_PROJECT": 2,
	}
)

func (x BrowseGiftsRequest_Type) Enum() *BrowseGiftsRequest_Type {
	p := new(BrowseGiftsRequest_Type)
	*p = x
	return p
}

func (x BrowseGiftsRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrowseGiftsRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_gifts_proto_enumTypes[0].Descriptor()
}

func (BrowseGiftsRequest_Type) Type() protoreflect.EnumType {
	return &file_gifts_proto_enumTypes[0]
}

func (x BrowseGiftsRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrowseGiftsRequest_Type.Descriptor instead.
func (BrowseGiftsRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{9, 0}
}

type Gift struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Specification *Gift_Specification `protobuf:"bytes,2,opt,name=specification,proto3" json:"specification,omitempty"`
}

func (x *Gift) Reset() {
	*x = Gift{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift) ProtoMessage() {}

func (x *Gift) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift.ProtoReflect.Descriptor instead.
func (*Gift) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{0}
}

func (x *Gift) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gift) GetSpecification() *Gift_Specification {
	if x != nil {
		return x.Specification
	}
	return nil
}

type RetrieveAvailableGiftsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetrieveAvailableGiftsRequest) Reset() {
	*x = RetrieveAvailableGiftsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveAvailableGiftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveAvailableGiftsRequest) ProtoMessage() {}

func (x *RetrieveAvailableGiftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveAvailableGiftsRequest.ProtoReflect.Descriptor instead.
func (*RetrieveAvailableGiftsRequest) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{1}
}

type RetrieveAvailableGiftsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gifts []*Gift `protobuf:"bytes,1,rep,name=gifts,proto3" json:"gifts,omitempty"`
}

func (x *RetrieveAvailableGiftsReply) Reset() {
	*x = RetrieveAvailableGiftsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveAvailableGiftsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveAvailableGiftsReply) ProtoMessage() {}

func (x *RetrieveAvailableGiftsReply) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveAvailableGiftsReply.ProtoReflect.Descriptor instead.
func (*RetrieveAvailableGiftsReply) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveAvailableGiftsReply) GetGifts() []*Gift {
	if x != nil {
		return x.Gifts
	}
	return nil
}

type CreateGiftsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gifts []*Gift_Specification `protobuf:"bytes,1,rep,name=gifts,proto3" json:"gifts,omitempty"`
}

func (x *CreateGiftsRequest) Reset() {
	*x = CreateGiftsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGiftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGiftsRequest) ProtoMessage() {}

func (x *CreateGiftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGiftsRequest.ProtoReflect.Descriptor instead.
func (*CreateGiftsRequest) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGiftsRequest) GetGifts() []*Gift_Specification {
	if x != nil {
		return x.Gifts
	}
	return nil
}

type CreateGiftsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GiftIds []string `protobuf:"bytes,1,rep,name=gift_ids,json=giftIds,proto3" json:"gift_ids,omitempty"`
}

func (x *CreateGiftsReply) Reset() {
	*x = CreateGiftsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGiftsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGiftsReply) ProtoMessage() {}

func (x *CreateGiftsReply) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGiftsReply.ProtoReflect.Descriptor instead.
func (*CreateGiftsReply) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGiftsReply) GetGiftIds() []string {
	if x != nil {
		return x.GiftIds
	}
	return nil
}

type DeleteGiftsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GiftIds []string `protobuf:"bytes,1,rep,name=gift_ids,json=giftIds,proto3" json:"gift_ids,omitempty"`
}

func (x *DeleteGiftsRequest) Reset() {
	*x = DeleteGiftsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGiftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGiftsRequest) ProtoMessage() {}

func (x *DeleteGiftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGiftsRequest.ProtoReflect.Descriptor instead.
func (*DeleteGiftsRequest) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGiftsRequest) GetGiftIds() []string {
	if x != nil {
		return x.GiftIds
	}
	return nil
}

type DeleteGiftsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteGiftsReply) Reset() {
	*x = DeleteGiftsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGiftsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGiftsReply) ProtoMessage() {}

func (x *DeleteGiftsReply) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGiftsReply.ProtoReflect.Descriptor instead.
func (*DeleteGiftsReply) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{6}
}

type ClaimGiftsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GiftIds []string `protobuf:"bytes,1,rep,name=gift_ids,json=giftIds,proto3" json:"gift_ids,omitempty"`
}

func (x *ClaimGiftsRequest) Reset() {
	*x = ClaimGiftsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimGiftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimGiftsRequest) ProtoMessage() {}

func (x *ClaimGiftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimGiftsRequest.ProtoReflect.Descriptor instead.
func (*ClaimGiftsRequest) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimGiftsRequest) GetGiftIds() []string {
	if x != nil {
		return x.GiftIds
	}
	return nil
}

type ClaimGiftsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClaimGiftsReply) Reset() {
	*x = ClaimGiftsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimGiftsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimGiftsReply) ProtoMessage() {}

func (x *ClaimGiftsReply) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimGiftsReply.ProtoReflect.Descriptor instead.
func (*ClaimGiftsReply) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{8}
}

type BrowseGiftsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemsPerPage int32                     `protobuf:"varint,1,opt,name=items_per_page,json=itemsPerPage,proto3" json:"items_per_page,omitempty"`
	Next         string                    `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Types        []BrowseGiftsRequest_Type `protobuf:"varint,3,rep,packed,name=types,proto3,enum=grants.BrowseGiftsRequest_Type" json:"types,omitempty"`
}

func (x *BrowseGiftsRequest) Reset() {
	*x = BrowseGiftsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrowseGiftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseGiftsRequest) ProtoMessage() {}

func (x *BrowseGiftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseGiftsRequest.ProtoReflect.Descriptor instead.
func (*BrowseGiftsRequest) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{9}
}

func (x *BrowseGiftsRequest) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

func (x *BrowseGiftsRequest) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *BrowseGiftsRequest) GetTypes() []BrowseGiftsRequest_Type {
	if x != nil {
		return x.Types
	}
	return nil
}

type BrowseGiftsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Next  string  `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items []*Gift `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BrowseGiftsReply) Reset() {
	*x = BrowseGiftsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrowseGiftsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseGiftsReply) ProtoMessage() {}

func (x *BrowseGiftsReply) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseGiftsReply.ProtoReflect.Descriptor instead.
func (*BrowseGiftsReply) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{10}
}

func (x *BrowseGiftsReply) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *BrowseGiftsReply) GetItems() []*Gift {
	if x != nil {
		return x.Items
	}
	return nil
}

type Gift_Specification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title            string                                `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                                `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ResourcesOwnedBy string                                `protobuf:"bytes,3,opt,name=resources_owned_by,json=resourcesOwnedBy,proto3" json:"resources_owned_by,omitempty"`
	Resources        []*GrantApplication_AllocationRequest `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	Criteria         []*UserCriteria                       `protobuf:"bytes,5,rep,name=criteria,proto3" json:"criteria,omitempty"`
}

func (x *Gift_Specification) Reset() {
	*x = Gift_Specification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gifts_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gift_Specification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift_Specification) ProtoMessage() {}

func (x *Gift_Specification) ProtoReflect() protoreflect.Message {
	mi := &file_gifts_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift_Specification.ProtoReflect.Descriptor instead.
func (*Gift_Specification) Descriptor() ([]byte, []int) {
	return file_gifts_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Gift_Specification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Gift_Specification) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Gift_Specification) GetResourcesOwnedBy() string {
	if x != nil {
		return x.ResourcesOwnedBy
	}
	return ""
}

func (x *Gift_Specification) GetResources() []*GrantApplication_AllocationRequest {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Gift_Specification) GetCriteria() []*UserCriteria {
	if x != nil {
		return x.Criteria
	}
	return nil
}

var File_gifts_proto protoreflect.FileDescriptor

var file_gifts_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x69, 0x66, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67,
	0x72, 0x61, 0x6e, 0x74, 0x73, 0x1a, 0x0c, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x02, 0x0a, 0x04, 0x47, 0x69, 0x66, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x40, 0x0a, 0x0d,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x69, 0x66,
	0x74, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0d, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xf1,
	0x01, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x4f,
	0x77, 0x6e, 0x65, 0x64, 0x42, 0x79, 0x12, 0x48, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x72, 0x61, 0x6e,
	0x74, 0x73, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x12, 0x30, 0x0a, 0x08, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x52, 0x08, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x1b, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x67, 0x69, 0x66, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x52,
	0x05, 0x67, 0x69, 0x66, 0x74, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05,
	0x67, 0x69, 0x66, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72,
	0x61, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x67, 0x69, 0x66, 0x74, 0x73, 0x22, 0x2d,
	0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x69, 0x66, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x67, 0x69, 0x66, 0x74, 0x49, 0x64, 0x73, 0x22, 0x2f, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x69, 0x66, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x67, 0x69, 0x66, 0x74, 0x49, 0x64, 0x73, 0x22, 0x12,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x2e, 0x0a, 0x11, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x47, 0x69, 0x66, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x69, 0x66, 0x74, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x67, 0x69, 0x66, 0x74, 0x49,
	0x64, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x47, 0x69, 0x66, 0x74, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xdf, 0x01, 0x0a, 0x12, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65,
	0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x50, 0x65, 0x72, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x42,
	0x72, 0x6f, 0x77, 0x73, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x58, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x46, 0x4f,
	0x52, 0x5f, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x44, 0x5f, 0x42, 0x59, 0x5f, 0x4d, 0x59, 0x5f, 0x50, 0x52,
	0x4f, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x22, 0x4a, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x77, 0x73,
	0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12,
	0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x32, 0x9f, 0x02, 0x0a, 0x0c, 0x47, 0x69, 0x66, 0x74, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x69,
	0x66, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74,
	0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40,
	0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x47, 0x69, 0x66, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x67,
	0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x47, 0x69, 0x66, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x47, 0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x43, 0x0a, 0x0b, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73, 0x12,
	0x1a, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x47,
	0x69, 0x66, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72,
	0x61, 0x6e, 0x74, 0x73, 0x2e, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x47, 0x69, 0x66, 0x74, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x31, 0x0a, 0x19, 0x64, 0x6b, 0x2e, 0x73, 0x64, 0x75, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5a, 0x14, 0x75, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x64, 0x6b, 0x2f, 0x61, 0x70,
	0x6d, 0x2f, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gifts_proto_rawDescOnce sync.Once
	file_gifts_proto_rawDescData = file_gifts_proto_rawDesc
)

func file_gifts_proto_rawDescGZIP() []byte {
	file_gifts_proto_rawDescOnce.Do(func() {
		file_gifts_proto_rawDescData = protoimpl.X.CompressGZIP(file_gifts_proto_rawDescData)
	})
	return file_gifts_proto_rawDescData
}

var file_gifts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gifts_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gifts_proto_goTypes = []interface{}{
	(BrowseGiftsRequest_Type)(0),               // 0: grants.BrowseGiftsRequest.Type
	(*Gift)(nil),                               // 1: grants.Gift
	(*RetrieveAvailableGiftsRequest)(nil),      // 2: grants.RetrieveAvailableGiftsRequest
	(*RetrieveAvailableGiftsReply)(nil),        // 3: grants.RetrieveAvailableGiftsReply
	(*CreateGiftsRequest)(nil),                 // 4: grants.CreateGiftsRequest
	(*CreateGiftsReply)(nil),                   // 5: grants.CreateGiftsReply
	(*DeleteGiftsRequest)(nil),                 // 6: grants.DeleteGiftsRequest
	(*DeleteGiftsReply)(nil),                   // 7: grants.DeleteGiftsReply
	(*ClaimGiftsRequest)(nil),                  // 8: grants.ClaimGiftsRequest
	(*ClaimGiftsReply)(nil),                    // 9: grants.ClaimGiftsReply
	(*BrowseGiftsRequest)(nil),                 // 10: grants.BrowseGiftsRequest
	(*BrowseGiftsReply)(nil),                   // 11: grants.BrowseGiftsReply
	(*Gift_Specification)(nil),                 // 12: grants.Gift.Specification
	(*GrantApplication_AllocationRequest)(nil), // 13: grants.GrantApplication.AllocationRequest
	(*UserCriteria)(nil),                       // 14: grants.UserCriteria
}
var file_gifts_proto_depIdxs = []int32{
	12, // 0: grants.Gift.specification:type_name -> grants.Gift.Specification
	1,  // 1: grants.RetrieveAvailableGiftsReply.gifts:type_name -> grants.Gift
	12, // 2: grants.CreateGiftsRequest.gifts:type_name -> grants.Gift.Specification
	0,  // 3: grants.BrowseGiftsRequest.types:type_name -> grants.BrowseGiftsRequest.Type
	1,  // 4: grants.BrowseGiftsReply.items:type_name -> grants.Gift
	13, // 5: grants.Gift.Specification.resources:type_name -> grants.GrantApplication.AllocationRequest
	14, // 6: grants.Gift.Specification.criteria:type_name -> grants.UserCriteria
	4,  // 7: grants.GiftsService.CreateGifts:input_type -> grants.CreateGiftsRequest
	6,  // 8: grants.GiftsService.DeleteGifts:input_type -> grants.DeleteGiftsRequest
	8,  // 9: grants.GiftsService.ClaimGifts:input_type -> grants.ClaimGiftsRequest
	10, // 10: grants.GiftsService.BrowseGifts:input_type -> grants.BrowseGiftsRequest
	5,  // 11: grants.GiftsService.CreateGifts:output_type -> grants.CreateGiftsReply
	7,  // 12: grants.GiftsService.DeleteGifts:output_type -> grants.DeleteGiftsReply
	9,  // 13: grants.GiftsService.ClaimGifts:output_type -> grants.ClaimGiftsReply
	11, // 14: grants.GiftsService.BrowseGifts:output_type -> grants.BrowseGiftsReply
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_gifts_proto_init() }
func file_gifts_proto_init() {
	if File_gifts_proto != nil {
		return
	}
	file_grants_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gifts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gift); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveAvailableGiftsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveAvailableGiftsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGiftsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGiftsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGiftsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGiftsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimGiftsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimGiftsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrowseGiftsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrowseGiftsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gifts_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gift_Specification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gifts_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gifts_proto_goTypes,
		DependencyIndexes: file_gifts_proto_depIdxs,
		EnumInfos:         file_gifts_proto_enumTypes,
		MessageInfos:      file_gifts_proto_msgTypes,
	}.Build()
	File_gifts_proto = out.File
	file_gifts_proto_rawDesc = nil
	file_gifts_proto_goTypes = nil
	file_gifts_proto_depIdxs = nil
}
