package dk.sdu.cloud.http

// Based on https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
val statusCodeReasons = run {
    val arr = Array(600) { "S$it" }

    arr[100] = "Continue"
    arr[101] = "Switching Protocols"
    arr[102] = "Processing"
    arr[103] = "Early Hints"

    arr[200] = "OK"
    arr[201] = "Created"
    arr[202] = "Accepted"
    arr[203] = "Non-Authoritative Information"
    arr[204] = "No Content"
    arr[205] = "Reset Content"
    arr[206] = "Partial Content"
    arr[207] = "Multi-Status"
    arr[208] = "Already Reported"
    arr[226] = "IM Used"

    arr[300] = "Multiple Choices"
    arr[301] = "Moved Permanently"
    arr[302] = "Found"
    arr[303] = "See Other"
    arr[304] = "Not Modified"
    arr[305] = "Use Proxy"
    arr[306] = "Switch Proxy"
    arr[307] = "Temporary Redirect"
    arr[308] = "Permanent Redirect"

    arr[400] = "Bad Request"
    arr[401] = "Unauthorized"
    arr[402] = "Payment Required"
    arr[403] = "Forbidden"
    arr[404] = "Not Found"
    arr[405] = "Method Not Allowed"
    arr[406] = "Not Acceptable"
    arr[407] = "Proxy Authentication Required"
    arr[408] = "Request Timeout"
    arr[409] = "Conflict"
    arr[410] = "Gone"
    arr[411] = "Length Required"
    arr[412] = "Precondition Failed"
    arr[413] = "Payload Too Large"
    arr[414] = "URI Too Long"
    arr[415] = "Unsupported Media Type"
    arr[416] = "Range Not Satisfiable"
    arr[417] = "Expectation Failed"
    arr[418] = "I'm a teapot"
    arr[421] = "Misdirected Request"
    arr[422] = "Unprocessable Entity"
    arr[423] = "Locked"
    arr[424] = "Failed Dependency"
    arr[425] = "Too Early"
    arr[426] = "Upgrade Required"
    arr[428] = "Precondition Required"
    arr[429] = "Too Many Requests"
    arr[431] = "Request Header Fields Too Large"
    arr[451] = "Unavailable For Legal Reasons"

    arr[500] = "Internal Server Error"
    arr[501] = "Not Implemented"
    arr[502] = "Bad Gateway"
    arr[503] = "Service Unavailable"
    arr[504] = "Gateway Timeout"
    arr[505] = "HTTP Version Not Supported"
    arr[506] = "Variant Also Negotiates"
    arr[507] = "Insufficient Storage"
    arr[508] = "Loop Detected"
    arr[510] = "Not Extended"
    arr[511] = "Network Authentication Required"

    arr
}
